### ISSUE TITLE
livereload.js bug

### ISSUE THREAD

**Issue by sruloart** [lucamezzalira/haxe-watchify#10]
Windows Script Host
script:
C:\users\user\AppData\Roaming\npm\node_modules\haxe-watchify\node_modules\liverreloadx\bin\livereloadx.js
Line: 1
Char: 1
Error: Invalid character
Code: 800A03F6
Source: Microsoft Jscript compilation error

**Comment by lucamezzalira** [comment]
Can you please share the parameters you've used in order to have that error? From the error message seems you've passed a weird character ...

**Comment by halfabench** [comment]
Question: when I use the livereload feature it opens livereloadx.jx in the notepad with the following code: 

...
  #!/usr/bin/env node
  require('../lib/cli').run();

Is it ok?

**Comment by lucamezzalira** [comment]
Let me investigate on that! 
Thanks for the check!

**Comment by sruloart** [comment]
I have the code, only on my PC Windows refuses to open the file (with the error I've described above, maybe UAC stuff?). I'll try to look into it as well, I really want to test the live-reload option already :)

**Comment by lucamezzalira** [comment]
ok, I've just tried on mac and it's working properly, I'll check it tonight I hope to solve it asap :+1: 
thanks to rise the bug

**Comment by sruloart** [comment]
Yeah, it looks like it's Windows only, I don't know why exactly. 

However, the workaround was pretty stupid really: since the .js files are associated with the Windows Script Host (for some reason, thank you Microsoft!), I just right-clicked>open with and set it to use node.exe instead. 

That also explains why a wild NOTEPAD appeared for @halfabench (his .js files are associated with it). 

The issue as a whole might be connected to these issues, but I haven't got the slightest idea :) :
---https://github.com/jrburke/r.js/issues/369
---https://github.com/npm/npm/issues/6674

**Comment by lucamezzalira** [comment]
good spot!
tonight I'm going to work on this, thanks for driving me in the right direction :+1:

**Comment by lucamezzalira** [comment]
Solved in version 1.2.1
