### ISSUE TITLE
Server: Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by sruloart** [lucamezzalira/haxe-watchify#14]
The server shuts down after a while with this error:  
`error starting livereload server! Error: stdout maxBuffer exceeded.`

Building is fine and is great, I'll be reviewing it today and the whole Sunday :)

**Comment by lucamezzalira** [comment]
probably it's related to issue #11

**Comment by lucamezzalira** [comment]
It's possible fixed increasing the maxBuffer size, you'll find in the next release

**Comment by lucamezzalira** [comment]
just released the new version please update and check if it's fixed :+1:

**Comment by sruloart** [comment]
Yep, that fixed it! :)

**Comment by lucamezzalira** [comment]
Nice :-)

**Comment by sruloart** [comment]
The monitor also works, so that's also pretty Nice!
