### ISSUE TITLE
error installing

### ISSUE THREAD

**Issue by MatthijsKamstra** [lucamezzalira/haxe-watchify#2]
I got this error:

```
→ npm install haxe-watchify -g
 
> fsevents@0.3.6 install /usr/local/lib/node_modules/haxe-watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

2015-07-04 15:25:35.256 xcodebuild[22313:929957] [MT] PluginLoading: Required plug-in compatibility UUID XXXXXXXXXXXXXXXXXXXXXX for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
make: *** No rule to make target `../../../../../../../../../../Volumes/Data', needed by `Makefile'.  Stop.
```

probably because my disk name is 'Data HD' (with a space in between)
But not sure if its your plugin or something else

**Comment by lucamezzalira** [comment]
I've just tried on a new empty folder to install it locally and it's working for me.
I'll investigate what could be this issue

<img width="605" alt="screen shot 2015-07-04 at 19 16 41" src="https://cloud.githubusercontent.com/assets/210272/8508987/4fa5e3ba-2281-11e5-8fb5-f83dd27848ff.png">

**Comment by lucamezzalira** [comment]
it looks like a problem of the unity plugin:
https://developer.appcelerator.com/question/160136/pluginloading-required-plug-in-compatibility-uuid-for-plug-in-at-path--not-present-in-dvtplugincompatibilityuuids

try to remove it and re-install haxe-watchify.

Let me know if it helps!

**Comment by MatthijsKamstra** [comment]
removed it and tried again, got the next error:
```
→ npm install haxe-watchify -g
 
> fsevents@0.3.6 install /usr/local/lib/node_modules/haxe-watchify/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

make: *** No rule to make target `../../../../../../../../../../Volumes/Data', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/haxe-watchify/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.6
/usr/local/bin/haxe-watchify -> /usr/local/lib/node_modules/haxe-watchify/src/haxe-watchify.js
haxe-watchify@1.1.0 /usr/local/lib/node_modules/haxe-watchify
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── chalk@1.1.0 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
└── chokidar@1.0.3 (arrify@1.0.0, path-is-absolute@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.1, readdirp@1.3.0, anymatch@1.3.0)
```

**Comment by lucamezzalira** [comment]
it looks installed because it arrives to install all the dependencies, try to type ```haxe-watchify``` in your terminal and let me know if it starts or not

In the meanwhile I'm going to check the gyp error.
BTW which OS are you working on?

**Comment by MatthijsKamstra** [comment]
```
→ haxe-watchify
ERROR: it's missing hx-watch.json and you didn't add the right parameters when you launch haxe-watchify!
```

OSX Yosemite
10.10.4

**Comment by lucamezzalira** [comment]
nice so it's installed now!!!

that is the error when you run haxe-watchify without any parameters or in a folder where hx-watch.json file is not present in the folder.
In order to use it check the [haxe-watchify instructions](https://github.com/lucamezzalira/haxe-watchify/blob/master/README.md).

**Comment by lucamezzalira** [comment]
the gyp error that you've got probably it's related to a conflict between the python version and node-gyp
Check if [this thread](http://stackoverflow.com/questions/21155922/error-installing-node-gyp-on-ubuntu) can help you... :dancers:

**Comment by MatthijsKamstra** [comment]
It works, nice!

**Comment by lucamezzalira** [comment]
:+1:
