### ISSUE TITLE
add support for other files to watch

### ISSUE THREAD

**Issue by francescoagati** [lucamezzalira/haxe-watchify#6]
with erazor and other templates macro should be nice watch also other files like css, and html.
So when a template change the project is recompiled

**Comment by lucamezzalira** [comment]
yep it's already in the backlog!
I don't know if I'll be able to work on that for next release but after the next one for sure I'll focus my effort there!
Thanks so much for the suggestion

**Comment by francescoagati** [comment]
Thanks to you. i'am using with linux ubuntu and works good.


2015-07-08 14:40 GMT+02:00 luca mezzalira <notifications@github.com>:

**Comment by lucamezzalira** [comment]
nice to know there are also linux users that are using HW :+1:

**Comment by MatthijsKamstra** [comment]
+1 I am currently working on a php project, so that would be awesome indeed

**Comment by lucamezzalira** [comment]
added new files watched in release 1.2.0 please read the readme file for more information
