### ISSUE TITLE
Current build process number

### ISSUE THREAD

**Issue by halfabench** [lucamezzalira/haxe-watchify#8]
Sometimes, I wonder if a compilation has really happened. For instance, if something I just coded does not work, I wonder if it's because I made a mistake or if the compiler has not processed the file yet.

So if I had some build number for the current session It would allow for clarity because I could remember what was the last one and be sure a new one has happened.
Maybe adding datetime + current changed file size would allow for even more clarity?

Well my 50cents ;)

**Comment by lucamezzalira** [comment]
fair point, I'll think about that :D

**Comment by lucamezzalira** [comment]
added at the end of the build a date and time value 1.2.0
